### ISSUE TITLE
Mouse appears to be used after Vim exits when running under tmux

### ISSUE THREAD

**Issue by lilydjwg** [jszakmeister/vim-togglecursor#43] opened 2019-03-22 13:41 UTC
Recently I find that after exiting Vim, my mouse is still a pointer instead of the I beam, indicating that the program inside the terminal is controlling the mouse.

Uninstalling this plugin things are back to normal. My tmux is version 2.8 and I only notice this recently. My Vim is the latest and my terminal is xfce4-terminal.

**Comment by jszakmeister** [comment] 2019-03-22 14:34
This is essentially a duplicate of #40.

**Closed by jszakmeister** 2019-03-22 14:34 UTC

**Comment by lilydjwg** [comment] 2020-12-05 10:28
With `env -u TMUX vim` this issue disappears and the cursor changes as expected. tmux version is 3.1_c.

I'm not commenting under #40 because I do not reproduce what that issue describes (with or without the `TMUX` env).
